version: '3.7'
services:
  client-instance:
    container_name: client-instance
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
      - "3001:3001"
      - "5006:5006"
